---
Name: myroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'DonationProceed': 'DonatePage_Controller'
    'UpdateDownloadsTask': 'UpdateDownloadsTask'
    'UpdateDownloadsPortable': 'UpdateDownloadsPortable'
